# Generated by Django 2.2.16 on 2023-02-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
            migrations.RenameField('Comment', 'created', 'pub_date'),
    ]
